name: Build and Deploy WellbeingHub API (SP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  RG: 'WellbeingHubRG'
  APP: 'wellbeinghub-api-uk'
  PUBLISH_DIR: 'publish'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ${{ env.PUBLISH_DIR }}

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ZIP deploy the published output to your Web App (no publish profile needed)
      - name: Deploy with Azure CLI
        run: az webapp deploy --resource-group ${{ env.RG }} --name ${{ env.APP }} --type zip --src-path ${{ env.PUBLISH_DIR }}
